Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian12"
    # first machine (Server)
    config.vm.define "pbureeraS" do |server|
      server.vm.hostname = "pbureeraS"
      server.vm.network "private_network", ip: "192.168.56.110"
      server.vm.provider "virtualbox" do |vb|
        vb.name = "pbureeraS"
        vb.memory = "512"
        vb.cpus = 1
      end
      server.vm.provision "shell" , privileged: true, path: "./scripts/installServer.sh"
    end
  
    # second machine (ServerWorker)
    config.vm.define "pbureeraSW" do |worker|
      worker.vm.hostname = "pbureeraSW"
      worker.vm.network "private_network", ip: "192.168.56.111"
      worker.vm.provider "virtualbox" do |vb|
        vb.name = "pbureeraSW"
        vb.memory = "512"
        vb.cpus = 1
      end
      worker.vm.provision "shell" , privileged: true, path: "./scripts/installWorker.sh"
    end
  end
