Vagrant.configure("2") do |config|

	config.vm.box = "generic/alpine312"

    config.vm.define "pbureeraS" do |server|
        server.vm.hostname = "pbureeraS"
        server.vm.network "private_network", ip: "192.168.56.110"
        server.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--name", "pbureeraS"]
            v.memory = 512
            v.cpus = 1
        end
        server.vm.provision "shell", path: "scripts/setupServer.sh"
    end

    config.vm.define "pbureeraSW" do |worker|
        worker.vm.hostname = "pbureeraSW"
        worker.vm.network "private_network", ip: "192.168.56.111"
        worker.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--name", "pbureeraSW"]
            v.memory = 512
            v.cpus = 1
        end
        worker.vm.provision "shell", path: "scripts/setupWorker.sh"
    end
end