Vagrant.configure("2") do |config|
  
	config.vm.box = "generic/debian12"

	config.vm.define "pbureeraS" do |guest|

		guest.vm.hostname = "pbureeraS"
		guest.vm.network "private_network", ip: "192.168.56.110"
		guest.vm.synced_folder "./confs", "/vagrant"
		guest.vm.provision "shell", path: "scripts/setupServer.sh"
        guest.vm.provider "virtualbox" do |vm|
                vm.memory = 512
                vm.cpus = 1
        end
	end

	config.vm.define "pbureeraSW" do |guest|

		guest.vm.hostname = "pbureeraSW"
		guest.vm.network "private_network", ip: "192.168.56.111"
		guest.vm.synced_folder "./confs", "/vagrant"
		guest.vm.provision "shell", path: "scripts/setupWorker.sh"
		guest.vm.provider "virtualbox" do |vm|
			vm.memory = 512
			vm.cpus = 1
		end
	end

end
